[package]
name = "scripts"
version = "0.1.0"
edition = "2024"

[dependencies]
ahash = "0.8.12"
clap = { version = "4.5.53", features = ["derive"] }
rayon = "1.11.0"

[[bin]]
name = "rCRUXMini__ParseAmpliconBlast"
path = "./src/bin/parse_amplicon_blast.rs"